// Generated by https://quicktype.io

export interface Items {
  status:    number;
  statusMsg: string;
  result:      Result;
}

export interface Result {
  categories: string[];
  author:     Author;
  items:      Item[];
}

export interface Author {
  name:     string;
  lastname: string;
}

export interface Item {
  id:            string;
  title:         string;
  price:         Price;
  picture:       string;
  condition:     string;
  free_shipping: boolean;
}

export interface Price {
  currency: string;
  amount:   number;
  decimals: number;
}
